### PR TITLE
checked_get_track_list: fix fail on Spotify

### LINKED ISSUE #70: Player::get_track_list fails with Spotify
I've tried testing [the ProgressTracker example](https://github.com/Mange/mpris-rs/blob/master/examples/progress_tracker.rs) to adapt it to output json eventually, but I get a panic when trying to run it:
`thread 'main' panicked at 'D-Bus call failed: Failed to call method'`

It seems to fail on `player.track_progress()`. I've dug through the code and, a few functions deep, found that the culprit is `get_track_list()`.

This only happens for Spotify afaict. I've tried YouTube on Firefox and `ncspot`, and these don't seem to have the issue. Perhaps Spotify incorrectly reports the existence of `org.mpris.MediaPlayer2.TrackList`?

### PR DESCRIPTION
**Pull request by fufexan**
Fixes #70.
The cause of the issue was that Spotify reports that it supports tracklists, but doesn't actually send one through MPRIS. This change ensures we don't try to get the tracklist unless a player actually has one available.

### CODE REVIEW

**Comment by fufexan** [comment]
@Mange could you review when you have the time?

File: src/player.rs [hunk 1]
```diff
@@ -392,7 +392,7 @@ impl Player {
     /// See [`get_track_list`](Self::get_track_list) and [`supports_track_lists`](Self::supports_track_lists)
     /// if you want to manually handle compatibility checks.
```
Comment (Mange) [inline src/player.rs]: Please reference the extra checking function in the documentation comment too.

**Review by Mange — CHANGES_REQUESTED** [review]
Sounds good to me! Well done finding the root cause of this issue!

I'll merge this after a tiny change.
Would you mind adding an entry to the Changelog too?

File: src/player.rs (hunk 1 above)
Comment (fufexan) [reply src/player.rs]: Sure!

**Review by Mange — APPROVED** [review]
Very nice! Thank you so much. :heart:
